---
title: "User Defined Validation Plan"
author: "Nathan Morris"
date: "1/28/2021"
output: html_document
---

# Purpose of this document
This document describes the "user defined validation plan" as descriped in "Develop, Validate, and Execute Code." Thus, it documents the steps to be taken to reasonably ensure this package functions according to specifications. The function documentation and vignettes serve as the specifications.

# Rationale

Since this is a package with limited scope that will be installed and/or used by other applications, many of the supporting deliverables that are typical for computer system validation are not applicable. The Security plan is not required, because any security functionality to control use of the package is the responsibility of the application using the package. Access to the code is controlled by GitHub. Furthermore, the package will rely on GitHub Backup/Restoration and Disaster Recovery of the source code. Applications that incorporate the package are responsible for their own Disaster Recovery and Backup/Restoration processes. The Business Continuity Plan is the responsibility of the application that incorporates the package. This package may be placed on CRAN.  


# Roles
The following roles will be involved in validation:

 + Code Author
 + Second Progammer 

## Automated Testing of Edge Cases
Many cases of clearly incorrect inputs are automatically tested in this package to ensure the package correctly throws errors and warnings. These include edge cases for the following 2 functions:

 + bootstrap_param_est()
 + impute()
 
> The code for these edge cases can be found in the file "/niaidMI/tests/testthat/test-edge-cases.R". 

## Automated Testing of 'bootstrap_param_est' and 'impute' functionality:

Test cases were created for 'bootstrap_param_est' and 'impute' with the following description:

1. Data is simulated by the sim_data() function and double programming was used to demonstrate that results from the model fit including parameter estimates and the log-likelhood calculations yield the same results. The tolerance of equal is `sqrt(.Machine$double.eps)=1.490116e-08` in our machine.

2. Imputation function is tested for strata and non-strata separately with double programming. The imputation sets are compared with the yardstick that empirical transition matrix and empirical initial distribution. The distribution of states at each time points is not used because it requires a much bigger number of imputations which is time-consuming. The tolerance of equal is defined as 0.01 for non-strata and 0.05 for strata. When generating data, homogeneous assumption is applied in order to reduce number of imputations required. Number of imputations is set as 100

> The code for these tests can be found in the file "/niaidMI/tests/testthat/test-est.R" and "/niaidMI/tests/testthat/test-imp.R".

# Revisions

## Version Control
The source code for this package is stored in a secured GitHub repository. Semantic versioning (https://semver.org/) will be utilized for version numbering starting with version 0.1.0.

## Revise Code

When changes are made to the code, the SOPs should be followed. Since the code is in a version controlled repository, all code changes and the rationale for the modifications are traceable with GitHub. The code will be reviewed for accuracy when a new revision of the package is released, per the automated processes described above.

## Periodic Review Strategy

Since this is an R package and not a full application, it will have a limited periodic review. The validation documentation (including training information) will be reviewed for accuracy when a new revision of the package is released. Automated testing will be performed when the updated package is built. Given the limited scope of this package, any incidents, problems, deviations, action items, and changes will be reviewed when they are occur and addressed as applicable. No additional monitoring or trending will be performed.